# Site settings
title: Steele Recruiting
email: ryan@steelerecruiting.us
number: (801) 946-6427
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: Steelerecruitin
facebook_username: steelerecruiting
googleplus_username: https://plus.google.com/118125862156127637859
linkedin_username: steelerecruiting

# Build settings
markdown: kramdown
